CONTIKI_PROJECT = udp-client udp-server
TARGET = simplelink
BOARD = srt/cc1352p

all: $(CONTIKI_PROJECT)

CONTIKI=../..
CORE_SDK=$(CONTIKI)/arch/cpu/simplelink-cc13xx-cc26xx/lib/coresdk_cc13xx_cc26xx
include $(CONTIKI)/Makefile.include
